apiVersion: apps/v1
kind: Deployment
metadata:
  name: always-401-backend
spec:
  selector:
    matchLabels:
      app: always-401-backend
  template:
    metadata:
      labels:
        app: always-401-backend
    spec:
      containers:
      - name: always-401-backend
        image: alantang888/always-error-401:1.0.0
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: always-401-backend
  labels:
    app: always-401-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: always-401-backend
